apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: my-example
  namespace: flink
spec:
  image: yunf66/flink-demo-image:flink-demoimage
  flinkVersion: v1_16
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "2"
  serviceAccount: flink
  jobManager:
    resource:
      memory: "2048m"
      cpu: 1
  taskManager:
    resource:
      memory: "2048m"
      cpu: 1
  job:
    jarURI: local:///opt/flink/usrlib/feature-demo-task-1.0.0-SNAPSHOT.jar
    parallelism: 2
    upgradeMode: stateless
