apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: my-example
  namespace: flink
spec:
  image: flink:1.16
  flinkVersion: v1_16
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "2"
  serviceAccount: flink
  jobManager:
    resource:
      memory: "2048m"
      cpu: 1
  taskManager:
    resource:
      memory: "2048m"
      cpu: 1
  job:
    jarURI: https://s01.oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=io.github.cyffff&a=feature-demo-task&v=1.0.0-SNAPSHOT&e=jar
    parallelism: 2
    upgradeMode: stateless
